### ISSUE TITLE
Wrong type in ServerClient.getOutboundMessages

### ISSUE THREAD

**Issue by santiagopuentep** [ActiveCampaign/postmark.js#114]
The `fromDate` value of the parameter of `getOutboundMessages` says it should be of type `string` but sending a String throws a runtime error telling that it expects a date.

This executes correctly but throws a Type error:

```
client.getOutboundMessages({
	recipient: "test@blackhole.postmarkapp.com",
	// this shows "Type 'Date' is not asignable to type 'string'
	fromDate: new Date(),
})
```

**Comment by SMKH-PRO** [comment]
try this: 

```
new Date().toISOString()
```

**Comment by ibalosh** [comment]
Hi @santiagopuentep 

the response error messages that you are receiving are the ones coming from Postmark API, not from the Postmark NodeJS library. NodeJS library only forwards the issue API noticed.

In this particular case, if you try something like:

```
client.getOutboundMessages({fromDate: '2022-03-01'}).then( result => {
  console.log(result);
})
```

you should see filter working. In API documentation, you can check out the format used for dates: https://postmarkapp.com/developer/api/messages-api

The reason why NodeJS is using string, is since we did not want to risk JS implementation of date passing incorrect parameter in some cases to the Postmark API. By providing string date that corresponds to what API expects, result will always be correct.

I do think though that we might want to improve the error message, so I will create a ticket for our team with details.

**Comment by santiagopuentep** [comment]
> try this:
> 
> ```
> new Date().toISOString()
> ```

That worked. Thanks.

@ibalosh Yes, it would be great to have the docs clarify all this and improve the error message. Thanks.
