### ISSUE TITLE
Unable to send email template within Cloudflare Worker

### ISSUE THREAD

**Issue by kpetrillo** [ActiveCampaign/postmark.js#123]
I have a Nuxt 3 project and am calling a server API route to send an email template. Everything is working locally, but when I push to my Cloudflare Worker, I get the following error: 

```
{
    message: "(h2.adapter || qi.adapter) is not a function",
    stack: "",
    statusCode: 500,
    statusMessage: "",
    url: "/api/postmark"
}
```

**Comment by ibalosh** [comment]
Hi @kpetrillo 

unfortunately we don't have experience with Cloudfare Worker, so we can't identify what the issue could be there. Since it works locally and those functions (h2 and qi adapter) are not something we can see within our library, it seems the issue is with cloudfare worker setup, maybe some of the libraries needed there are not installed properly.

**Comment by kpetrillo** [comment]
Thank you for the response. If you do not see the error on your end, that will help me narrow things down. Thanks!

**Comment by kpetrillo** [comment]
Yea, I think you're right. I've run into similar limitations. That's okay, though, I could just send fetch requests via your API. The wrappers are nice, but I can live without them. Thanks for your help!
