### ISSUE TITLE
Update axios version

### ISSUE THREAD

**Issue by richardsimko** [ActiveCampaign/postmark.js#142]
Is there a possibility for you to upgrade Axios to at least 1.6.0 to adress CVE-2023-45857?

**Comment by levpachmanov** [comment]
Hey @richardsimko,
We're part of a startup called Seal Security that mitigates software vulnerabilities in older open source versions by backporting/creating standalone security patches - enabling more straightforward remediation in cases like this. We created an axios 0.27.2-sp1 that's vulnerability-free. As with all of our patches, it's open-source and available for free.

If relevant, check out [our GitHub repo](https://github.com/seal-community/patches/tree/main/npm/axios/0.27.2/sp1) if you wish to learn more, or start using our [app](https://app.sealsecurity.io/?ref=ghaxios).

Please feel free to reach us at [info@seal.security](mailto:info@seal.security) if you have any requests/questions.

**Comment by ibalosh** [comment]
Hi there,

postmark.js is not affected by the vulnerability, because we are not using `withCredentials: true` when creating instances, nor we plan to.

I will close this task and keep the [PR](https://github.com/ActiveCampaign/postmark.js/pull/141) to make a decision with the team which direction we want to take regarding axios, node version support etc.

Will keep you posted in the PR.
